name: Deploy to heroku

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build 
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: FirstSecurity.jar
          path: backend/target/FirstSecurity.jar


  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: First Security App
      url: https://toweroftrust.herokuapp.com
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v2
        with:
          name: FirstSecurity.jar  #Must be the same as 'finalName' in pom.xml
          path: backend/target
      - name: Login to heroku
        run: heroku container:login
      - name: Push docker container
        run: heroku container:push web -a toweroftrust #Change with your heroku-app name
      - name: Deploy docker container
        run: heroku container:release web -a toweroftrust #Change with your heroku-app name